FROM python:3.10-slim-buster

LABEL maintainer="Kumar S"
ARG DEBIAN_FRONTEND=noninteractive

# Make sure the package repository is up to date.
RUN apt-get update && \
    apt-get -qy full-upgrade && \
    apt-get install -qy git && \
# Install a basic SSH server
    apt-get install -qy openssh-server && \
    sed -i 's|session    required     pam_loginuid.so|session    optional     pam_loginuid.so|g' /etc/pam.d/sshd && \
    mkdir -p /var/run/sshd && \
# Install JDK 11
    apt-get install -qy openjdk-11-jdk && \
# Cleanup old packages
    apt-get -qy autoremove && \
    apt-get install -qy curl && \
# Add user jenkins to the image
    useradd -ms /bin/bash jenkins && \
# Set password for the jenkins user (you may want to alter this).
    echo "jenkins:jenkins" | chpasswd && \
    mkdir /home/jenkins/.m2

#ADD if reqd- settings.xml /home/jenkins/.m2/
# Copy authorized keys if reqd
#COPY .ssh/authorized_keys /home/jenkins/.ssh/authorized_keys

# This is for testing only. Have a reqts.txt in same folder
COPY reqts.txt /home/jenkins/reqts.txt

RUN chown -R jenkins:jenkins /home/jenkins/

# Standard SSH port
EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]